name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Install dependencies
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake build-essential
          sudo apt-get install -y \
            libfreetype6-dev \
            libx11-dev \
            libxrandr-dev \
            libudev-dev \
            libgl1-mesa-dev \
            libflac-dev \
            libsndfile1-dev \
            libvorbis-dev \
            libvorbisenc2 \
            libvorbisfile3 \
            libopenal-dev \
            libpthread-stubs0-dev \
            libjpeg8-dev \
            libxcursor-dev \
            libxi-dev

      # 3. Configure the project using CMake
      - name: Configure project (CMake)
        shell: bash
        run: |
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCYBERSERPENT_GENERATE_INSTALLER=TRUE

      # 4. Build the project
      - name: Build project
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # 4. Package the build using CPack
      - name: Generate package (CPack)
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: sudo cpack -G "TGZ"

  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Install CMake
      - name: Install CMake
        run: choco install -y cmake nsis

      # 3. Configure the project using CMake
      - name: Configure project (CMake)
        run: |
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCYBERSERPENT_GENERATE_INSTALLER=TRUE

      # 4. Build the project
      - name: Build project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # 4. Package the build using CPack
      - name: Generate package (CPack)
        working-directory: ${{github.workspace}}/build
        run: |
          cpack -G "NSIS;ZIP"

